<html>
<head>
<?php
echo '<title>My First PHP Script</title>';
?>
</head>
<body>
<?php
       echo '<p>This content was generated by PHP</p>';
?>
<p>And this content is static HTML</p>
</body>
</html>
